### ISSUE TITLE
Comment and Documentation cleanup

### ISSUE THREAD

**Issue by ajaj895** [WIU-Computer-Science-Association/csa-twitterbot#1]
There are a lot of code that I've commented out, cleaning this up would make it nicer to read and look at.

**Comment by Caps-Looking** [comment]
Can I take this?

**Comment by ajaj895** [comment]
You can if you want, the code is going to be changing a bunch in the coming weeks just to let you know.

**Comment by Caps-Looking** [comment]
There are some commented codes, these codes should be removed or I just have to clean the other comments?

**Comment by ajaj895** [comment]
Yeah that's fine, sorry for the late reply, that can get cleaned up too.
